In [1]:
import torch;

In [2]:
a = torch.rand((10,8))
print(a)
b = torch.reshape(a,(a.shape[0],2,4))
print(b)

tensor([[0.0485, 0.8932, 0.8309, 0.8046, 0.6337, 0.8927, 0.2013, 0.7389],
        [0.3874, 0.5154, 0.7585, 0.6921, 0.3586, 0.5990, 0.2594, 0.4618],
        [0.8112, 0.9150, 0.1771, 0.1257, 0.4604, 0.8026, 0.2851, 0.9915],
        [0.5011, 0.9062, 0.5779, 0.3181, 0.1155, 0.3808, 0.0930, 0.7579],
        [0.4198, 0.4676, 0.7315, 0.6334, 0.8605, 0.7082, 0.5503, 0.7406],
        [0.8642, 0.0671, 0.3788, 0.4232, 0.8472, 0.1555, 0.8436, 0.8971],
        [0.1472, 0.4751, 0.4156, 0.3002, 0.1246, 0.2419, 0.8170, 0.4650],
        [0.9817, 0.4969, 0.8025, 0.6477, 0.5907, 0.2358, 0.4387, 0.3833],
        [0.8471, 0.2403, 0.1871, 0.2700, 0.4044, 0.7224, 0.3479, 0.2839],
        [0.9208, 0.5029, 0.6105, 0.2581, 0.4970, 0.7939, 0.3608, 0.0966]])
tensor([[[0.0485, 0.8932, 0.8309, 0.8046],
         [0.6337, 0.8927, 0.2013, 0.7389]],

        [[0.3874, 0.5154, 0.7585, 0.6921],
         [0.3586, 0.5990, 0.2594, 0.4618]],

        [[0.8112, 0.9150, 0.1771, 0.1257],
         [0.4604, 0.8026, 0.2851, 0.9915

In [15]:
n = 5
e = n*n
edge_index = torch.zeros((2,e))
print(edge_index)
print(edge_index.shape)
for i in range(0,e):
    edge_index[0,i] = i // n
    edge_index[1,i] = i % n
print(edge_index)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0.]])
torch.Size([2, 25])
tensor([[0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 3., 3., 3.,
         3., 3., 4., 4., 4., 4., 4.],
        [0., 1., 2., 3., 4., 0., 1., 2., 3., 4., 0., 1., 2., 3., 4., 0., 1., 2.,
         3., 4., 0., 1., 2., 3., 4.]])


In [4]:
a = torch.rand((5,3,2))

In [5]:
print(a)
print(a[1,:,:])

tensor([[[0.2089, 0.4295],
         [0.0624, 0.5655],
         [0.7671, 0.7745]],

        [[0.4760, 0.8801],
         [0.6491, 0.1533],
         [0.9163, 0.0271]],

        [[0.1040, 0.9655],
         [0.5627, 0.1571],
         [0.1281, 0.1107]],

        [[0.8109, 0.1771],
         [0.3739, 0.0580],
         [0.7196, 0.2410]],

        [[0.5378, 0.8088],
         [0.1018, 0.7556],
         [0.2380, 0.5257]]])
tensor([[0.4760, 0.8801],
        [0.6491, 0.1533],
        [0.9163, 0.0271]])


In [9]:
import torch
from torch_geometric.data import Data
from torch_geometric.loader import DataLoader

n = 10
f = 2
x = torch.rand((n,f))
edge_index = (torch.rand((2,n*n))*n).type(torch.long)
data1 = Data(x=x, edge_index=edge_index)
print(data1)
print(data1.x)
print(data1.edge_index)

x = torch.rand((n,f))
edge_index = (torch.rand((2,n*n))*n).type(torch.long)
data2 = Data(x=x, edge_index=edge_index)
print(data2)
print(data2.x)
print(data2.edge_index)


dl = DataLoader([data1,data2],batch_size=2)
print(dl)
data_batched = next(iter(dl))
print(data_batched)
print(data_batched.x)
print(data_batched.edge_index)
print(data_batched.batch)



Data(x=[10, 2], edge_index=[2, 100])
tensor([[0.9324, 0.1171],
        [0.8885, 0.6334],
        [0.5080, 0.1578],
        [0.9090, 0.6431],
        [0.2934, 0.0440],
        [0.8276, 0.0052],
        [0.6715, 0.1483],
        [0.0988, 0.9280],
        [0.3849, 0.9854],
        [0.2397, 0.8654]])
tensor([[7, 1, 5, 8, 0, 9, 9, 0, 8, 2, 7, 9, 9, 2, 7, 8, 8, 2, 5, 0, 5, 7, 7, 8,
         2, 1, 5, 6, 6, 3, 0, 2, 5, 4, 4, 5, 8, 6, 4, 2, 5, 5, 3, 4, 8, 5, 3, 8,
         2, 8, 1, 8, 3, 6, 7, 8, 0, 3, 8, 4, 7, 8, 9, 6, 6, 2, 7, 3, 7, 5, 4, 2,
         9, 5, 0, 8, 5, 0, 2, 2, 4, 7, 0, 6, 7, 8, 2, 4, 5, 2, 8, 7, 5, 9, 3, 7,
         2, 1, 5, 1],
        [2, 2, 3, 3, 4, 2, 5, 6, 3, 0, 0, 9, 3, 0, 1, 6, 9, 4, 7, 6, 8, 3, 5, 2,
         5, 9, 4, 9, 0, 0, 5, 4, 4, 2, 5, 2, 3, 7, 0, 8, 2, 6, 5, 8, 7, 4, 2, 7,
         0, 4, 2, 4, 7, 1, 5, 0, 0, 0, 7, 4, 1, 0, 2, 2, 8, 1, 7, 7, 8, 5, 7, 7,
         3, 9, 7, 6, 9, 6, 8, 7, 5, 5, 5, 5, 0, 2, 3, 7, 3, 7, 6, 5, 6, 2, 9, 7,
         1, 6, 4, 8]])
Data(x=[1

In [10]:
a = [1,2,3]
print(a)
a.append(4)
print(a)

[1, 2, 3]
[1, 2, 3, 4]


In [13]:
from torch_geometric.nn.pool import global_max_pool, global_mean_pool, global_add_pool

out = torch.ones((10,3))
batch = torch.tensor([1,1,1,3,3,2,2,2,2,0])
out_batched = global_add_pool(out,batch)
print(out_batched)

tensor([[1., 1., 1.],
        [3., 3., 3.],
        [4., 4., 4.],
        [2., 2., 2.]])


In [56]:
from torch_geometric.nn.models import MLP


mlp = MLP(in_channels=4, hidden_channels=10,out_channels=3, num_layers=3,norm="LayerNorm")
a = torch.rand((5,4))
batch = torch.tensor([0,0,1,1,1])
print(batch)
print(a)
b = mlp(a,batch=batch)
print(b)
a[0,2] = 10
# print(a)
bb = mlp(a,batch=batch)
print(bb)
bb = mlp(a,batch=batch)
print(bb)

tensor([0, 0, 1, 1, 1])
tensor([[0.6074, 0.6452, 0.1208, 0.9893],
        [0.9779, 0.0286, 0.5620, 0.3042],
        [0.2244, 0.8329, 0.2577, 0.6064],
        [0.1047, 0.3346, 0.0607, 0.9325],
        [0.3456, 0.9321, 0.0516, 0.6733]])
tensor([[-0.8157,  0.2007, -0.2416],
        [-0.5607,  0.4942, -0.0242],
        [ 0.0747, -0.0112, -0.2458],
        [ 0.3878,  0.3769, -0.0562],
        [ 0.0442, -0.2806, -0.4053]], grad_fn=<AddmmBackward0>)
tensor([[-1.0887e+00,  7.0507e-01, -6.1435e-01],
        [-1.2277e-01,  2.1238e-02,  1.5695e-01],
        [ 5.7557e-02,  1.2694e-02, -9.3746e-02],
        [ 6.2242e-02, -6.3487e-04, -5.9142e-02],
        [ 6.2487e-02, -1.6546e-02, -9.0535e-02]], grad_fn=<AddmmBackward0>)
tensor([[-1.0887e+00,  7.0507e-01, -6.1435e-01],
        [-1.2277e-01,  2.1238e-02,  1.5695e-01],
        [ 5.7557e-02,  1.2694e-02, -9.3746e-02],
        [ 6.2242e-02, -6.3487e-04, -5.9142e-02],
        [ 6.2487e-02, -1.6546e-02, -9.0535e-02]], grad_fn=<AddmmBackward0>)


In [5]:
import numpy as np

a = np.zeros((3,3), dtype=np.int8)
b = np.zeros((3,3), dtype=np.int8)
b[1,0] = 1
b[0,1] = 1
b[2,0] = 1
print(b)
print(a)
a[b==1] = 3
print(a)
print("AAA")
print(np.where(b==1))

[[0 1 0]
 [1 0 0]
 [1 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 3 0]
 [3 0 0]
 [3 0 0]]
AAA
(array([0, 1, 2]), array([1, 0, 0]))


In [ ]:
# from torch_geometric.nn.models import MLP
from torchvision.ops import MLP

mlp = MLP(in_channels=4, hidden_channels=[10,10,3])
a = torch.rand((5,4))
batch = torch.tensor([0,1,2,3,4])
print(a)
b = mlp(a)
print(b)
a[0,2] = 1000
# print(a)
bb = mlp(a)
print(bb)
bb = mlp(a)
print(bb)

In [30]:
import torch as th
import numpy as np
a = np.zeros((3,4))
print(a)
i1 = np.array([0,1,0], dtype=np.int8)
ii1= np.where(i1 == 1)[0]
i2 = np.array([0,0,0,1],dtype=np.int8)
ii2 = np.where(i2==1)[0]
a[ii1,ii2] = 1
print(a)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(array([1]),)
